server:
  port: 8081

party:
  notify:
    batch-size: 100
    time-out: 3600000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: ENC(90m2KrOoF1jFAMQxn4P4JA==)
    password: ENC(augoSRpuMpFZhWeajEkGTqo5e9eyaa2e)

  jpa:
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: none
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ENC(LpM4QrKYjTSSQk33mNnbdyjqPRm+eIlO7hQEKtiFCKavRBl8PFV5gcUXOVjFFF4S)
    username: ENC(AYc9538zUIMEWTOc2jCJnWJmpzKhdXpy)
    password: ENC(m4S3uxQO2eV/OEZdREvW/LTMYPKIX7nB)
  jpa:
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ENC(jS2wzNJvOrPEc/qcEcNnftkETXyXQE28zXekY0SR5zLsNTnhOh4qyllq2AnSZQ7kH3xK66wyZFvDvd4ql/uDZUtFclmubrMIb9ZGAd6ll3TyY8P4n0lR6sIOAsYeZCDW)
    username: ENC(zdrkAKUJiXdo4sztev9kQw==)
    password: ENC(r2BUekYDafkZJUokhA1vvZrWDVMqNzl7)
  jpa:
    show-sql: false
